### ISSUE TITLE
elf2e32 for toolchain

### ISSUE THREAD

**Issue by pent0** [bentokun/symbian-clang#1]
- Allow morden compile elf2e32 to Linux.
- Waiting for fedor4ever/elf2e32#1 to be merged.

**Comment by pent0** [comment]
Thanks @fedor4ever!

**Comment by fedor4ever** [comment]
@bentokun, add to friends - https://steamcommunity.com/id/fedor4ever/ =)

**Comment by pent0** [comment]
sure, didnt notice :D
